publish_frequency: 5.0
update_frequency: 15.0
global_frame: map
robot_base_frame: base_link
rolling_window: false
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
plugins:
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: inflater, type: "costmap_2d::InflationLayer"}
  - {name: human_layer_static, type: "cohan_layers::StaticAgentLayer"}
  - {name: human_layer_visible, type: "cohan_layers::AgentVisibilityLayer"}
inflater:
    inflation_radius: 0.2
static_map:
  enabled:              true
  map_topic:            "/map"
human_layer_static:
  robot_radius: 0.46
  agent_radius: 0.31
